### ISSUE TITLE
Remote access to postgres database

### ISSUE THREAD

**Issue by scottyhq** [snowex-hackweek/jupyterhub#3]
A feature request that would be useful is allowing remote access to the database from a machine outside of the jupyterhub cluster VPC. For example, how can we explore this database from QGIS running on a laptop? There are two requirements for this:

1. The database must be configured to allow access for given user credentials 

2. The EC2 instance with the database must have certain ports open (can be open to any IP, or restricted to certain ranges of IPs) https://github.com/snowex-hackweek/jupyterhub/blob/7adb37f9880808eb01517c4f24a5dafc40638870/terraform/eks/ec2_postgres.tf#L22 

cc @lsetiawan @aaarendt @micahjohnson150

**Comment by micahjohnson150** [comment]
* For the db, I believe we needed to add a line to /etc/postgresql/13/main/pg_hba.conf file like the following for external users:
`host    snowex          snow            0.0.0.0/0               md5
`
* Which says user snow can access the snowex db from any ip. I also created the same user with read access only inside the db. 

I add those things on Friday I think so we should be good to go on the DB configuration front.
